# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)

        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Window, QtGui.QColor("#ECECEC"))
        MainWindow.setPalette(palette)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.btnSeleccionarCarpeta = QtWidgets.QPushButton(self.centralwidget)
        self.btnSeleccionarCarpeta.setGeometry(QtCore.QRect(10, 10, 150, 30))
        self.btnSeleccionarCarpeta.setObjectName("btnSeleccionarCarpeta")

        self.btnSeleccionarCarpeta.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 5px;
                padding: 5px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
            QPushButton:pressed {
                background-color: #3c9039;
            }
        """)

        self.btnGenerarEstructura = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerarEstructura.setGeometry(QtCore.QRect(10, 50, 150, 30))
        self.btnGenerarEstructura.setObjectName("btnGenerarEstructura")

        self.btnGenerarEstructura.setStyleSheet("""
            QPushButton {
                background-color: #2196F3;
                color: white;
                border: none;
                border-radius: 5px;
                padding: 5px;
            }
            QPushButton:hover {
                background-color: #1e8bc3;
            }
            QPushButton:pressed {
                background-color: #1976a9;
            }
        """)

        self.lineEditCarpeta = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCarpeta.setGeometry(QtCore.QRect(167, 10, 400, 30))
        self.lineEditCarpeta.setObjectName("lineEditCarpeta")
        self.lineEditCarpeta.setReadOnly(True)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setCentralWidget(self.centralwidget)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnSeleccionarCarpeta.setFont(font)
        self.btnGenerarEstructura.setFont(font)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSeleccionarCarpeta.setText(_translate("MainWindow", "Seleccionar Carpeta"))
        self.btnGenerarEstructura.setText(_translate("MainWindow", "Generar Estructura"))
